ci:
  skip: [cargo-fmt, cargo-clippy]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: fix-byte-order-marker
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/joshuadavidthomas/ast-grep-rules
    rev: v0.5.0
    hooks:
      - id: rust
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        entry: just fmt --check
        language: system
        types: [rust]
        pass_filenames: false
      - id: cargo-clippy
        name: cargo clippy
        entry: cargo clippy --locked --all-targets --all-features -- -D warnings
        language: system
        types: [rust]
        pass_filenames: false
  - repo: https://github.com/woodruffw/zizmor-pre-commit
    rev: v1.30.1
    hooks:
      - id: zizmor
